"""
Django settings for interface project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from os import getenv
from corsheaders.defaults import default_methods, default_headers
from django.utils.translation import gettext_lazy as _
DATABASE_ENGINE = getenv("DATABASE_ENGINE","sqlite3")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}


BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = "django-insecure-0=_^0tqg+pkc#m6q#*20izp96#)-52c&&xby#r3d1(!--8ig9%"
DEBUG = True
ALLOWED_HOSTS = ["*"]

SITE_ID = getenv("DJANGO_SITE_ID",1)
INSTALLED_APPS = [
    "whitenoise",
    "corsheaders",
    "admin_interface",
    "colorfield",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.flatpages",
    "django_extensions",
    "django_filters",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "import_export",
    "monotremata",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.flatpages.middleware.FlatpageFallbackMiddleware",
    "monotremata.middleware.GlobalRequestMiddleware"
]
ROOT_URLCONF = "interface.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "monotremata" / "templates", BASE_DIR / "templates"],
        # "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                "apptemplates.Loader",
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
            ],
        },
    }
]
WSGI_APPLICATION = "interface.wsgi.application"
ASGI_APPLICATION = "interface.asgi.application"
DATABASES = {
    "spatialite": {
        "ENGINE": "django.contrib.gis.db.backends.spatialite",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "postgresql": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenv("DB_NAME", "monotremata"),
        "USER": getenv("DB_USER", "monotremata"),
        "PASSWORD": getenv("DB_PASSWORD", "admin1234"),
        "HOST": getenv(
            "DB_HOST", "ge-postgres.database.svc.cluster.local"
        ),
        "PORT": getenv("DB_PORT", "5432"),
    },
    "postgis": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": getenv("DB_NAME", "notebook"),
        "USER": getenv("DB_USER", "notebook"),
        "PASSWORD": getenv("DB_PASSWORD", "admin1234"),
        "HOST": getenv("DB_HOST", "ge-postgres.database.svc.cluster.local"),
        "PORT": getenv("DB_PORT", "5432"),
    },
    "sqlite3": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]
LANGUAGES = (
    ("en", _("English")),
    ("de", _("Deutsh")),
    ("it", _("Italiano")),
    ("fr", _("Français")),
    # more than one language is expected here
)
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "media/"

REST_FRAMEWORK = {
    "PAGE_SIZE": 100,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
}


SIMPLE_JWT = {
    # "SIGNING_KEY": "SECRET_KEY",
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60 * 24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("JWT",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=50),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
    "CHECK_REVOKE_TOKEN": False,
    "REVOKE_TOKEN_CLAIM": "hash_password",
    "CHECK_USER_IS_ACTIVE": True,
}


WEB_TITLE = getenv("MONOTREMATA_SWAGGER_TITLE", "Monotremata 🦔")
# /api/swagger
SPECTACULAR_SETTINGS = {
    "OAS_VERSION": "3.0.3",
    "TITLE": WEB_TITLE + " API",
    "DESCRIPTION": "Management System",
    "VERSION": getenv("API_VERSION", "1.1"),
    "SERVE_INCLUDE_SCHEMA": True,
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        # "url": "/api/v0/schema/",
    },
}

SWAGGER_SETTINGS = {
    "LOGIN_URL": "rest_framework:login",
    "LOGOUT_URL": "rest_framework:logout",
}

ALLOWED_UPLOAD_EXTENSIONS = [
    "csv",
    "csvw",
    "yaml",
    "json",
    "txt",
    "xlsx",
    "xls",
    "png",
    "pdf",
    "odt",
    "ods",
    "doc",
    "docx",
    "md",
    "xml",
    "css",
    "txt",
    "svg",
    "zip",
    "json-ld",
    "ttl",
    "n3",
    "html",
]

FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880 * 2  # 10 MB
GIT_ADMIN_USER = getenv("GIT_ADMIN_USER", "amir")
GIT_ADMIN_PASSWORD = getenv("GIT_ADMIN_PASSWORD", "")
GIT_HOST = getenv("GIT_HOST", "forgejo.forgejo.svc.cluster.local")
GIT_URL = getenv("GIT_URL", "http://forgejo.forgejo.svc.cluster.local")
SERVICE_URL = getenv("SERVICE_URL", "http://monotremata.monotremata.svc.cluster.local")
SERVICE_HOST = getenv("SERVICE_HOST", "monotremata.monotremata.svc.cluster.local")
JUPYTER_SERVER_PORT = getenv("JUPYTER_SERVER_PORT", "8001")
JUPYTER_SERVER_HOST_IP = getenv("JUPYTER_SERVER_HOST_IP", "0.0.0.0")
JUPYTER_SERVER_HOST_PROTOCOL = getenv("JUPYTER_SERVER_HOST_PROTOCOL", "http")
JUPYTER_SERVER_HOST = getenv(
    "JUPYTER_SERVER_HOST", f"{JUPYTER_SERVER_HOST_PROTOCOL}://{JUPYTER_SERVER_HOST_IP}"
)
JUPYTER_SERVICE_URL = getenv(
    "JUPYTER_SERVICE_URL", f"{JUPYTER_SERVER_HOST}:{JUPYTER_SERVER_PORT}"
)


JUPYTER_WEBPATH = getenv("JUPYTER_WEBPATH", "")
NOTEBOOK_ARGUMENTS = [
    "--ip",
    JUPYTER_SERVER_HOST_IP,
    "--port",
    JUPYTER_SERVER_PORT,
    "--notebook-dir",
    f"{BASE_DIR / 'interactive'}",
    "--autoreload",
    "--allow-root",
    "--no-browser",
    f"--ServerApp.token={getenv('JUPYTER_TOKEN', 'token1234')}",
    f"--NotebookApp.default_url='/{JUPYTER_WEBPATH}'",
    f"--ServerApp.base_url='/{JUPYTER_WEBPATH}'",
    f"--JupyterHub.bind_url=f'{JUPYTER_SERVICE_URL}'",
]

SHELL_PLUS_POST_IMPORTS = []

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]
