apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-monotremata.fullname" . }}
  labels: {{- include "helm-monotremata.labels" . | nindent 4 }}
data:
  SERVICE_PORT: '{{ .Values.service.port }}'
  {{- range $k, $v := .Values.environments }}
  {{ $v.name }}: '{{ $v.value }}'
  {{- end }}
